name: CMake Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/run-cmake@v2
      with:
        buildDirectory: 'target'

    - name: Install Valgrind
      run: sudo apt-get install valgrind

    - name: Add FTP User
      run: |
        sudo useradd ftplite-server
        echo "ftplite-server:ftplite1" | sudo chpasswd

    - name: Build
      run: cmake . && make -j4

    - name: Test
      run: ./test-e2e/server/start_server.sh & ./test-e2e/client/start_client.sh
