name: CMake Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/run-cmake@v2
      with:
        buildDirectory: 'target'

    - name: Build
      run: cmake . && make -j4

    - name: Test
      run: cd test-e2e/server && ../../target/bin/server 20715 & sleep 5 && cd test-e2e/client && ./script.sh | ../../target/bin/client localhost 27015
